# Generated by Django 2.0.6 on 2018-10-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAluno', models.CharField(max_length=20)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGrupo', models.CharField(max_length=100)),
                ('anoGrupo', models.DateField()),
                ('infoGrupo', models.TextField()),
                ('atvEnvolvidas', models.CharField(max_length=100)),
                ('statusGrupo', models.CharField(max_length=20)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProjeto', models.CharField(max_length=100)),
                ('anoProjeto', models.DateField()),
                ('infoProjeto', models.TextField()),
                ('atvEnvolvidas', models.CharField(max_length=100)),
                ('statusProjeto', models.CharField(max_length=100)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.Aluno')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.Professor'),
        ),
        migrations.AddField(
            model_name='alunogrupo',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.Professor'),
        ),
    ]
